### PR TITLE
release 2.1.1

### PR DESCRIPTION
**Pull request by taichunmin**
@phate09 Please help me update description in steam mods with there language.

# English

```
Automate gathering, chopping, digging, planting, fertilizing, traping and drying!

[Usage]
* Press key V to toggle chores wheel
* Press O to open in-game settings
* Support ChinesePlus for Traditional Chinese and Simplified Chinese.
* "Geometric Placement" mod messes up with the placement of plants. Hold CTRL when planting so that it temporarily disables geometric placement

Report bugs at: [url]https://github.com/phate09/ToDoChores/issues[/url]


## 2.1

* Now trap_teeth and beemine can be plant
* Now seeds and reeds can be pickup
* Try to fix predictive problem
```

- - -

# Traditional Chinese

```
自動採集、砍樹、挖掘、種樹、施肥、放陷阱、曬肉乾！

[預設使用方法]
* 預設使用 V 來開啟工作面板
* 預設使用 O 來開啟遊戲內設定
* 安裝 ChinesePlus 就可以顯示中文
* Geometric Placement 會導致本模組的種植功能異常，請避免同時使用

如果模組有任何 bug 請回報到：[url]https://github.com/phate09/ToDoChores/issues[/url]

## 2.1

* 現在可以種植尖牙陷阱和蜜蜂地雷
* 現在可以撿起所有種子和採集蘆葦
* 嘗試修復 predictive 的問題
```

- - -

# Simplified Chinese

```
自动采集、砍树、挖掘、种树、施肥、放陷阱、晒肉干！

[预设使用方法]
* 预设使用 V 来开启工作面板
* 预设使用 O 来开启游戏内设定
* 安装 ChinesePlus 就可以显示中文
* Geometric Placement 会导致本模组的种植功能异常，请避免同时使用

如果模组有任何 bug 请回报到：[url]https://github.com/phate09/ToDoChores/issues[/url]

## 2.1

* 现在可以种植尖牙陷阱和蜜蜂地雷
* 现在可以捡起所有种子和采集芦苇
* 尝试修复 predictive 的问题
```

### CODE REVIEW

**Comment by phate09** [comment]
has it been tested?

**Comment by taichunmin** [comment]
I have test that for one night. Please help me add there language description. Thanks!

**Comment by phate09** [comment]
I’ll push the changes tonight then, but unfortunately i cannot help you add the language description.
Hope it’s still ok

Best regards,
Edoardo

**Comment by taichunmin** [comment]
Language description can edit at steam workshop page. 😄

**Comment by taichunmin** [comment]
The language I write at PR's description. You can copy that.

**Comment by phate09** [comment]
Oh, i see, ok then i’ll also do that

**Comment by taichunmin** [comment]
Vezérszattyán report a nil bug because of locale is nil, so I update the code.
0V6jajW

**Comment by phate09** [comment]
Ok, i’ll wait for your confirmation

Best regards,
Edoardo

On 19 Jun 2019, at 17:34, 戴均民 <notifications@github.com<mailto:notifications@github.com>> wrote:


Vezérszattyán report a nil bug because of locale is nil, so I update the code.

**Comment by taichunmin** [comment]
I already fix that 😸

**Pull request merged**
